### ISSUE TITLE
Requested Clipboard operation did not succeed.

### ISSUE THREAD

**Issue by Fearswe** [horsedrowner/Superscrot#35]
Happened a second time.
Stacktrace:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Superscrot.Manager.<UploadScreenshot>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Superscrot.Manager.<KeyPressed>d__1c.MoveNext()

**Comment by horsedrowner** [comment]
Clone the [error-handling](https://github.com/horsedrowner/Superscrot/tree/error-handling) branch and build it yourself. Nothing is fixed yet, but it should show a more detailed message now, including the name of the application that has a lock on the Clipboard.

Simply retrying wouldn't work because `Clipboard.SetText` by default retries every 100 ms up to ten times. The ultimate solution would probably be to just show a simple dialog that shows the public URL in text box where you can copy it (like YouTube's HTML5 player), or maybe open the screenshot when you click on the balloon error message.

**Comment by Vivelin** [comment]
@Fearswe Is this still happening?

**Comment by Fearswe** [comment]
I haven't noticed it since. So no.
